### ISSUE TITLE
cannot boot into system

### ISSUE THREAD

**Issue by flymin** [xuzhao9/ThinkPad-X1E-Hackintosh#1]
I am using the [EFI files](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme) from Errrneist for a while and everything seems to work fine. However, my hardware configuration is exactly the same as yours (except for the wireless card, which I [changed](https://github.com/Errrneist/Hackintosh-Thinkpad-X1-Extreme/blob/master/IMG/Readme.MD) to use BT, and SSD, which are 7600p and 760p, both 256GB). 

I am using 8750H and 1080P no-touch screen with 16GB RAM, so I suspect that your EFI files are more compatible with my laptop than Errrneist's version. However, after I changed to use EFI files in your repo (I tried to add your /S/E files in the CLOVER kext folder as I have done before, or boot without these kexts added), my system will be stuck in the loading stage with a apple icon and loading bar growing slowly on the screen. 

Is there any slightly difference you suppose between your repo and Errrneist's files that may cause such problem? It seems really strange to me.

**Comment by xuzhao9** [comment]
First, please make sure you are using 1.23 BIOS same as mine.
Second, it could be SSDT_NVMe-Pcc.aml. If you are not using SAMSUNG PM981 SSD as your SSD1, do not use this SSDT.
I don't change anything wireless or BT related.

**Comment by flymin** [comment]
I updated BIOS to 1.23, still have the problem. And I also replaced aml files in ACPI/patch with ones I originally used, problem remains the same.
Here is the booting output with `-v` option in clover:

![efENO1.jpg](https://s2.ax1x.com/2019/08/06/efENO1.jpg)

**Comment by xuzhao9** [comment]
My machine took around 1min to boot, so the EFI in this repo works for my laptop.
This message indicates the problem is likely in the DSDT/SSDT tables you use (which is from this repo).
When I was using Errrneist's configuration, my system took ~25mins to boot, and that is probably what you see on your machine. That's why I handmaded the config myself. 
A reasonable guess is that your and Errrnist's machines are more similar, and my machine is another sub-model.
You can also try fix the DSDT and SSDT tables yourself and see what happens on your machine with your own BIOS.

**Comment by flymin** [comment]
Thank you for your answer. Since my laptop is also 8750H version, I cannot suspect any differences in hardware resulting in this problem so far. I will check DSDT/SSDT tables.

I will close this issue for now, and any progress will be acknowledged.
